
x_0: [0,0] # m
C: 1 # m/s
D: D # m2/s (Diffusion coefficient)
u_bg: [0,0] # m/s
threshold: threshold # m
t_max: t_max # s
t_init: t_init # s
steps_per_action: 5
nb_episode: 650
batch_size: 256
eval_freq: 50
save_model: True
eval_episodes: 8
episode_start_update: 10
path: path
tree: tree
p_0:  [0,0] # m
p_target: [2, 0] # m
start_timesteps: 256
load_model: ""
episode_per_update: 3
discount_factor: 1
beta: 0.5
uniform_bg: True # Random uniform background flow during the training
rankine_bg: True # Random rankine vortex during the training
pertubation_after_episode: 20 # Background flow add in the training after this episode
random_curve: True # To train on varying curve (no longer random)
nb_points_path: 500 # Discretization of the path
Dt_action: Dt_action
velocity_bool: True # Add the velocity in the state or not
n_lookahead: 10 # Number of points in the lookahead
velocity_ahead:  False
add_action : True
dim : 2
