ratio: 5
N: [576, 528]
start_point: [0.98, 0.3,0.4]
res_factor: 1
heuristic_weight: 3
weight_sdf: 1
sigma: 15
c: 0.2
B: 2
pow_v0: 7
pow_al: 5
max_radius : 1.5
description: "cant swim against the current (condition over v_l @ d >0), v0**7 and alignment ** 5 - 3D"